### ISSUE TITLE
Error while running tool

### ISSUE THREAD

**Issue by v3daxt** [josh0xA/darkdump#5]
![2022-01-12 13_57_31-Kali-Linux-2021 3-vbox-amd64  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/69508556/149091252-baf4207d-b7bb-47ac-9532-07bbfd5d9458.png)

**Comment by alexmoes** [comment]
darksearch.io does not allow any public queries anymore. Any plans to change to another search engine?

**Comment by josh0xA** [comment]
> 

Sorry for the delayed response. I will be updating the API very soon as I do like it when this tool works as planned even though I made it in one hour sitting on my bed (drunk).
