### ISSUE TITLE
errors in different modules

### ISSUE THREAD

**Issue by Yashparwal1** [josh0xA/darkdump#6]
![2022-04-10 11_34_19-New Issue · josh0xA_darkdump - Brave](https://user-images.githubusercontent.com/54176283/162604667-234142ea-7361-41b6-b1c4-c5424b561a6d.png)

**Comment by 9cat** [comment]
same here

**Comment by josh0xA** [comment]
Darkdump is fixed. The new version is ready for use. (Darkdump 2.0)
