### ISSUE TITLE
What's going on？

### ISSUE THREAD

**Issue by 12662** [josh0xA/darkdump#7]
HTTPSConnectionPool(host='darksearch.io', port=443): Max retries exceeded with url: /api/search?query=cats&page=1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
![image](https://user-images.githubusercontent.com/56062426/168097857-cb2cb48e-f77f-41e9-b12a-040fd41a32a3.png)

**Comment by parthk2510** [comment]
Getting the same error !!
UnboundLocalError: local variable 'json_data' referenced before assignment
Any solution provider ?

**Comment by Dom-Sathanas** [comment]
I'm having the same problem

![image](https://user-images.githubusercontent.com/72554584/181791030-83b9e9e9-9e24-4dbe-b193-b57ea3c07154.png)

**Comment by josh0xA** [comment]
Darkdump is fixed. The new version is ready for use. (Darkdump 2.0)
